### ISSUE TITLE
Window object does not have a setup_menu

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnumdk/eolie#1]
First bug :P 
```bash
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/eolie/application.py", line 148, in do_startup
    self.window.setup_menu(menu)
AttributeError: 'Window' object has no attribute 'setup_menu'
```

**Comment by julianrichen** [comment]
Just built master as of commit c00ac7d, I'm also seeing this issue:

```bash
$ eolie 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/eolie/application.py", line 149, in do_startup
    window.setup_menu(menu)
AttributeError: 'Window' object has no attribute 'setup_menu'
```

Seems commit e4c97a0 didn't do the trick?
