### ISSUE TITLE
Eolie don't want to start

### ISSUE THREAD

**Issue by M5oul** [gnumdk/eolie#148]
### Environment
- Eolie version: git@5d976507c6e2ad4c8998c2a8cc0a34a69c64694c
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: Fedora 26

### Bug

Eolie don't want to start:
```bash
eolie
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/eolie/application.py", line 507, in __on_command_line
    ephemeral)
  File "/usr/local/lib/python3.6/site-packages/eolie/container.py", line 84, in add_webview
    self.add_view(webview, parent, window_type)
  File "/usr/local/lib/python3.6/site-packages/eolie/container.py", line 106, in add_view
    self.__pages_manager.add_child(view)
  File "/usr/local/lib/python3.6/site-packages/eolie/pages_manager_listbox.py", line 50, in add_child
    self.__set_child_height(child)
  File "/usr/local/lib/python3.6/site-packages/eolie/pages_manager_listbox.py", line 99, in __set_child_height
    child.set_preview_height(ArtSize.PREVIEW_HEIGHT)
  File "/usr/local/lib/python3.6/site-packages/eolie/pages_manager_listbox_child.py", line 75, in set_preview_height
    self._overlay.set_size_request(-1, height)
AttributeError: 'PagesManagerListBoxChild' object has no attribute '_overlay'
```

**Comment by M5oul** [comment]
Ok, it's fixed.
