### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by M5oul** [gnumdk/eolie#149]
### Environment
- Eolie version: 0.9-140-ge90fc40
- GTK+ version: 3.22
- Operating system: Fedora 26

### Bug/Feature

```bash
Window::__show_source_code(): soup_request_error_quark: Nicht unterstütztes Adressenschema »about« (1)
Search::get_keywords(): g-io-error-quark: Vorgang wurde abgebrochen (19)

** (eolie:3185): CRITICAL **: Unsupported type void

** (eolie:3185): CRITICAL **: Unsupported type void
Gdk-Message: Unable to load none from the cursor theme
Gdk-Message: Unable to load none from the cursor theme
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/eolie/toolbar_title.py", line 455, in _on_key_press_event
    uri = El().search.get_search_uri(uri)
  File "/usr/local/lib/python3.6/site-packages/eolie/search.py", line 95, in get_search_uri
    return self.__search % words
TypeError: not all arguments converted during string formatting
```

**Comment by gnumdk** [comment]
Isn't your wikipedia search string missing %s? :)

**Comment by gnumdk** [comment]
Should be ok with current master:  fallback to Google...
