### ISSUE TITLE
Hold down F11 causes crash

### ISSUE THREAD

**Issue by City-busz** [gnumdk/eolie#155]
### Environment
- Eolie version: 0.9
- GNOME/GTK+ versions: 3.24.2/3.22.16
- GNU/Linux distribution: Arch Linux

### Bug
Press and hold down the F11 button, and you'll see the following crash:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/eolie/window.py", line 357, in __on_shortcut_action
    self.unfullscreen()
  File "/usr/lib/python3.6/site-packages/eolie/window.py", line 107, in unfullscreen
    GLib.idle_add(self.__fullscreen_toolbar.get_parent().destroy)
AttributeError: 'NoneType' object has no attribute 'get_parent'

**Comment by fastrizwaan** [comment]
yes, quikly pressing f11 keys multiple times crashes eolie; should ignore f11 key event till the window is fullscreen and vice versa

eolie 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/eolie/window.py", line 357, in __on_shortcut_action
    self.unfullscreen()
  File "/usr/lib/python3.6/site-packages/eolie/window.py", line 106, in unfullscreen
    self.disconnect_by_func(self.__on_motion_notify_event)
TypeError: nothing connected to <bound method Window.__on_motion_notify_event of <window.Window object at 0x7f32cc0b93f0 (eolie+window+Window at 0x56287d7fc2b0)>>
