### ISSUE TITLE
database_bookmarks.py:918:search:sqlite3.OperationalError: near "ORDER": syntax error

### ISSUE THREAD

**Issue by ebousse** [gnumdk/eolie#230]
### Environment
- Eolie version: 0.9.1-1-g68407fa
- GTK+ version: 3.22
- Operating system: Fedora 26

### Bug

~~~~~~
database_bookmarks.py:918:search:sqlite3.OperationalError: near "ORDER": syntax error

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/eolie/toolbar_title.py", line 868, in __on_entry_changed_timeout
    self.__popover.set_search_text(value)
  File "/usr/local/lib/python3.6/site-packages/eolie/popover_uri.py", line 456, in set_search_text
    self.__set_search_text(search)
  File "/usr/local/lib/python3.6/site-packages/eolie/popover_uri.py", line 994, in __set_search_text
    result += El().bookmarks.search(search, 15)
  File "/usr/local/lib/python3.6/site-packages/eolie/database_bookmarks.py", line 918, in search
    result = sql.execute(request, filters)
sqlite3.OperationalError: near "ORDER": syntax error

Local variables in innermost frame:
words_copy: []
request: 'SELECT title, uri                       FROM bookmarks WHERE                       bookmarks.guid != bookmarks.uri AND ORDER BY length(uri) ASC,                        popularity DESC, mtime DESC LIMIT ?'
filters: (15,)
sql: <sqlite3.Connection object at 0x7f404494db90>
items: []
words: []
limit: 15
search: ' '
self: <eolie.database_bookmarks.DatabaseBookmarks object at 0x7f4044942358>
~~~~~~

**Comment by gnumdk** [comment]
Does it happen everytime?

Can you send me this file by email?
~/.local/share/eolie/bookmarks.db

**Comment by ebousse** [comment]
Not sure how it happened, so hard to tell :(

I have sent my bookmarks by email.

**Comment by gnumdk** [comment]
Ok, so it's not the bookmark file :) I guess you pasted some unprintable chars in uribar.
