### ISSUE TITLE
I can not open Eolie after autoremove some files .

### ISSUE THREAD

**Issue by cgiannakidis70** [gnumdk/eolie#265]
### Environment
- Eolie version:0.9.7
- GNOME:3.26.1
- GNU/Linux distribution:
I autoremoved some files and after that i can not run anymore Eolie.I installed it again from ubuntu ppa and from git but the result is the same.Dependencies are met.
When i run it from terminal :

Traceback (most recent call last):
  File "/usr/local/bin/eolie", line 25, in <module>
    from eolie.application import Application
  File "/usr/local/lib/python3.6/site-packages/eolie/application.py", line 28, in <module>
    from eolie.window import Window
  File "/usr/local/lib/python3.6/site-packages/eolie/window.py", line 16, in <module>
    from eolie.toolbar import Toolbar
  File "/usr/local/lib/python3.6/site-packages/eolie/toolbar.py", line 16, in <module>
    from eolie.toolbar_title import ToolbarTitle
  File "/usr/local/lib/python3.6/site-packages/eolie/toolbar_title.py", line 20, in <module>
    from eolie.popover_uri import UriPopover
  File "/usr/local/lib/python3.6/site-packages/eolie/popover_uri.py", line 18, in <module>
    from dateutil import tz
ModuleNotFoundError: No module named 'dateutil'

**Comment by gnumdk** [comment]
??

**Comment by cgiannakidis70** [comment]
Hi.
I installed again with synaptic manager "dateutil" for python and now is opening again.

**Comment by gnumdk** [comment]
Will add it as dep
