### ISSUE TITLE
Errors while opening from CLI

### ISSUE THREAD

**Issue by M5oul** [gnumdk/eolie#35]
### Environement
- Eolie version: 0.4, git@fc08e8b8932f7b2a085d3e8551dc386e54b69026
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: Fedora 26 Alpha

### Bug
Opening a website or a local webpage from CLI, it display nothing and result with thoses errors:

```bash
eolie https://github.com
Application::init(): No module named 'Crypto'
Error calling 'extension.initialize': Traceback (most recent call last):
  File "/usr/local/share/eolie/webkitextension/extension.py", line 47, in initialize
    ProxyExtension(extension, forms)
  File "/usr/local/lib/python3.6/site-packages/eolie/extension_proxy.py", line 117, in __init__
    Server.__init__(self, self.__bus, PROXY_PATH)
  File "/usr/local/lib/python3.6/site-packages/eolie/extension_proxy.py", line 34, in __init__
    method_call_closure=self.on_method_call)
GLib.Error: g-io-error-quark: Für die Schnittstelle org.gnome.Eolie.Proxy auf /org/gnome/EolieProxy wurde bereits ein Objekt exportiert (2)
WebViewErrors::__on_web_process_crashed(): <view_web.WebViewMeta object at 0x7f001a75c3a8 (WebKitWebView at 0x5631f593b5d0)>
Bereits aktuell.
```

**Comment by gnumdk** [comment]
Please run with LANG=C and then paste output

**Comment by M5oul** [comment]
```bash
env LANG=C eolie https://github.com
Python detected LC_CTYPE=C: LC_CTYPE & LANG coerced to C.UTF-8 (set another locale or PYTHONCOERCECLOCALE=0 to disable this locale coercion behavior).
Application::init(): No module named 'Crypto'
Fontconfig warning: ignoring C.UTF-8: not a valid language tag
Error calling 'extension.initialize': Traceback (most recent call last):
  File "/usr/local/share/eolie/webkitextension/extension.py", line 47, in initialize
    ProxyExtension(extension, forms)
  File "/usr/local/lib/python3.6/site-packages/eolie/extension_proxy.py", line 117, in __init__
    Server.__init__(self, self.__bus, PROXY_PATH)
  File "/usr/local/lib/python3.6/site-packages/eolie/extension_proxy.py", line 34, in __init__
    method_call_closure=self.on_method_call)
GLib.Error: g-io-error-quark: An object is already exported for the interface org.gnome.Eolie.Proxy at /org/gnome/EolieProxy (2)
Already up-to-date.
WebViewErrors::__on_web_process_crashed(): <view_web.WebViewMeta object at 0x7f09147ab360 (WebKitWebView at 0x5612a8ec4fe0)>
```

**Comment by gnumdk** [comment]
Hmm , welcome to manual install :) Garbage file...

rm -fr /usr/local/lib/python3.6/site-packages/eolie

**Comment by gnumdk** [comment]
ls -l /usr/local/share/eolie/webkitextension/extension.py

**Comment by M5oul** [comment]
```bash
ls -l /usr/local/share/eolie/webkitextension/
insgesamt 160
-rw-r--r--. 1 root root  1699 30. Mai 14:21 extension.py
-rw-r--r--. 1 root root 82876 30. Mai 14:21 libpythonloader.a
-rwxr-xr-x. 1 root root  1044 30. Mai 14:21 libpythonloader.la*
lrwxrwxrwx. 1 root root    24 30. Mai 14:21 libpythonloader.so -> libpythonloader.so.0.0.0*
lrwxrwxrwx. 1 root root    24 30. Mai 14:21 libpythonloader.so.0 -> libpythonloader.so.0.0.0*
-rwxr-xr-x. 1 root root 54160 30. Mai 14:21 libpythonloader.so.0.0.0*
-rw-r--r--. 1 root root 11608 17. Mai 15:42 pythonloader.so
```

**Comment by gnumdk** [comment]
rm -fr /usr/local/share/eolie/webkitextension/

**Comment by M5oul** [comment]
Nice, it works fine.
