### ISSUE TITLE
Flatpatkref crashes on launch

### ISSUE THREAD

**Issue by bagage** [gnumdk/eolie#54]
### Environement
- Eolie version: flatpakref
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: Debian unstable

### Bug/Feature
The current flatpak ref from https://gnumdk.github.io/eolie-web/ crashes on startup. 

```
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/eolie/database_history.py", line 323, in get_opened_pages
    WHERE opened=1")
sqlite3.OperationalError: no such column: opened

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/eolie/menu_pages.py", line 143, in __append_opened_pages
    for (uri, title) in El().history.get_opened_pages():
  File "/app/lib/python3.5/site-packages/eolie/database_history.py", line 328, in get_opened_pages
    WHERE opened=1")
sqlite3.OperationalError: no such column: opened
```

**Comment by gnumdk** [comment]
Because you have run local version and flatpak one

**Comment by gnumdk** [comment]
Db-version to 0 in dconf editor

**Comment by gnumdk** [comment]
So bad idea to store this in dconf with flatpak
