### ISSUE TITLE
Crash closing a tab

### ISSUE THREAD

**Issue by M5oul** [gnumdk/eolie#59]
### Environement
- Eolie version: git@981e6e380682032999dce8bbf46fc602e11e6915
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: Fedora 26 Alpha/Beta

### Bug
When closing a tab, eolie crash:
```bash
eolie
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/eolie/stacksidebar_child.py", line 164, in _on_close_button_press_event
    self.__window.container.sidebar.close_view(self.__view)
  File "/usr/local/lib/python3.6/site-packages/eolie/stacksidebar.py", line 192, in close_view
    view.webview.get_session_state())
  File "/usr/local/lib/python3.6/site-packages/eolie/menu_pages.py", line 96, in add_action
    encoded = sha256(uri.encode("utf-8")).hexdigest()
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by gnumdk** [comment]
What type of page? Can't reproduce and it's strange uri is None :-/

**Comment by M5oul** [comment]
Seems fixed.
Thanks!
